// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
namespace labtest1
{
    internal class Program
    {
        static void Main(string[] args)
        {
          Console.WriteLine("C# program that takes a string and a word as input from the user, then checks whether the word is present in the string");
            Console.WriteLine("Entre the desired sentence");
          string inputs= Console.ReadLine();
          string wordTS=Console.ReadLine();
                      string inputS = Console.ReadLine();//user to enter a string.
            Console.WriteLine("entre a word");
            String wordTC = Console.ReadLine();//word to search within that string.

            if (ContainsWord(inputS, wordTC))
            {
                Console.WriteLine($"this is present in the entrered string {wordTC}");
            }
            else
            {
                Console.WriteLine($"this is not  present in the entred string {wordTC}");
            }
            static bool ContainsWord(string inputS, string wordTC)
            {
                //Both the input string and the search word are converted to lowercase to ensure the search is case-insensitive.
                string normalizatedinput = inputS.ToLower();
                string normalizatedword = wordTC.ToLower();

                return normalizatedinput.Contains(normalizatedword);//Contains method to check if the search word is present in the input string.
            }
        }
    }
}
